[build]
  command = "npm install && npm run build"
  publish = "dist"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  NODE_VERSION = "18"
  VITE_CLARIFAI_API_KEY = "0710f08dbba14e88892df385399f8695"
  VITE_CALORIE_NINJA_API_KEY = "9AWK9Jt/hdW4RBKFSPPApQ==zDIOA8e7Ci1fw8hJ"
  VITE_API_URL = "https://fittrack-1-yefe.onrender.com"
  VITE_CLIENT_URL = "https://flourishing-basbousa-b3c0d9.netlify.app"